#steps:
#  # Build the Angular app
#  - name: 'node:16.13.2'
#    entrypoint: npm
#    args: ['install']
#    dir: 'rapido'
#  - name: 'node:16.13.2'
#    entrypoint: npm
#    args: ['run', 'build']
#    dir: 'rapido'
#  # Build the Docker image
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/rapido-382018/1440', '.']
#    dir: '.'
#  # Push the Docker image to Container Registry
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'gcr.io/rapido-382018/1440']
#  # Deploy the Docker image to Compute Engine
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args:
#      - 'compute'
#      - 'instances'
#      - 'update-container'
#      - 'rapido'
#      - '--container-image=gcr.io/rapido-382018/1440'
#      - '--zone=europe-southwest1-a'
#      - '--container-env=NGINX_PORT=8080'
#      - '--container-mount-host-path=host-path=/var/log/nginx,mount-path=/var/log/nginx,mode=rw'
#
#


steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/rapido-382018/1440', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/rapido-382018/1440']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'digital', '--image', 'gcr.io/rapido-382018/1440', '--region', 'me-west1']
images:
  - gcr.io/rapido-382018/1440
